### ISSUE TITLE
Output custom HTML

### ISSUE THREAD

**Issue by pecuchet** [inspheric/nova-url-field#15]
I may be mistaken, but it does not seem possible to output custom HTML on the index and/or detail page? Since the `Url` field inherits from the default `Text` field, I expected things like `Text::asHtml()` to work. Is there any way prevent the HTML from being escaped?

**Comment by kitbs** [comment]
Hi @pecuchet 

It's not currently possible, no.

Although the PHP class extends the default Text field, the Vue component is specific to this package so that it displays the `<a href="...">` tag and the SVG icon (see [Url.vue](https://github.com/inspheric/nova-url-field/blob/master/resources/js/components/Url.vue)).

In your use case, would you want to display custom HTML _inside_ the existing styled `<a>` tag with icon, or would you want to _replace_ the whole tag with your custom content?

**Comment by pecuchet** [comment]
Hi @kitbs,

My use case is to replace the whole tag, and to display the URL as an image on the index and detail views. I hadn't checked the Vue component yet. It is indeed very specific to `<a>` tags. 

What do you think, would it be an idea to extend you package?

**Comment by kitbs** [comment]
Hi @pecuchet 

I have added two new `customHtml()` and `customHtmlUsing()` methods which will allow you to set your own HTML to replace the contents of the existing `<a>` tag.

You can also use `label(...)->asHtml()` if you want to keep the default icon but use some minor HTML within the label itself.

There is documentation at https://github.com/inspheric/nova-url-field/blob/custom-html/README.md#custom-html

These are only on the `custom-html` branch for now. If you want to test that and let me know if it suits your purposes, then I will release a new version with these changes.

Thanks for the idea!

**Comment by pecuchet** [comment]
Hi @kitbs,

Just perfect! I'm now using the `customHtmlUsing()` method on the `custom-html` branch and it works like a charm. Very handy to have included the `$resource` and `$label` parameters in the callback.

Thanks for the quick update!

**Comment by kitbs** [comment]
Excellent! I'm glad it does what you need.

I'll tag a new release shortly.

Cheers
