### ISSUE TITLE
noopener=true and noreferrer=false?

### ISSUE THREAD

**Issue by anibalsanchez** [inspheric/nova-url-field#21]
Hi,

In the code, only noopener is true by default.

    /**
     * The link tag's rel attribute.
     * @var array
     */
    protected $rel = ['noopener' => true];

In the README, it looks like both are true by default:

    Url::make('Homepage')
        ->noopener(bool $noopener = true),

    Url::make('Homepage')
        ->noreferrer(bool $noreferrer = true),

So, is the README wrong or does the default value have to be true for both?

    /**
     * The link tag's rel attribute.
     * @var array
     */
    protected $rel = ['noopener' => true, 'noreferrer' => true];

Great field! Thank you.

**Comment by kitbs** [comment]
Hi Anibal

The field will always have `noopener` by default, because that's what's declared in the `$ref` property of the class.

But if you also want `noreferrer`, you have to actually call the `noreferrer()` method on the field, where the default argument of the method is true.

You can also pass `false` as the argument to either method if you want to disable the behaviour.

Hope this helps!
